### 理解 NumPy 陣列的廣播規則(broadcasting)
#### 向量化運算：不用迴圈、直接讓陣列彼此相加、相乘

In [8]:
import numpy as np
# 建立 shape 為 (3, 1) 的 array_a 與 (1, 4) 的 array_b
array_a = np.ones((3, 1))
array_b = np.ones((1, 4))

# 相加後，打印出結果的矩陣形狀 shape ，應為 (3, 4)
array_c = array_a + array_b
print(f"相加後的矩陣形狀（列數、行數）")
print(np.shape(array_c))

相加後的矩陣形狀（列數、行數）
(3, 4)


#### 廣播並延展陣列

In [7]:
import numpy as np
# 建立 shape 為 (3, 1) 的 array_a 與 (1, 4) 的 array_b
array_a = np.array([[1], [2], [3]])
array_b = np.array([[10, 20, 30, 40]])

# 確認兩個 array 的內容，並使用 np.broadcast_to 顯示延展結果
broadcast_a = np.broadcast_to(array_a, (3, 4))
broadcast_b = np.broadcast_to(array_b, (3, 4))

# 印出延展前後的內容
print(f"橫向延展_column複製")
print(array_a)
print(broadcast_a)
print()

print(f"縱向延展_row複製")
print(array_b)
print(broadcast_b)
print()

# 兩個 array 是先透過延展再相加
array_c = array_a + array_b
c = broadcast_a + broadcast_b
print(f"延展並相加結果")
print(c)
print()

print(f"直接相加結果")
print(array_c)

橫向延展_column複製
[[1]
 [2]
 [3]]
[[1 1 1 1]
 [2 2 2 2]
 [3 3 3 3]]

縱向延展_row複製
[[10 20 30 40]]
[[10 20 30 40]
 [10 20 30 40]
 [10 20 30 40]]

延展並相加結果
[[11 21 31 41]
 [12 22 32 42]
 [13 23 33 43]]

直接相加結果
[[11 21 31 41]
 [12 22 32 42]
 [13 23 33 43]]


#### 遮罩與條件篩選

In [ ]:
import numpy as np

# 建立一個隨機陣列，包含十個數字
arr = np.random.rand(10)
print(arr)
print()

# 篩選條件：數字必須大於 0.5 ，符合者標為 True ，其餘為 False
arr_compare = arr > 0.5
print(arr_compare)
print()

# 使用 np.where，數字必須大於 0.5 ；符合條件者標記為 1 ；否則為 0 。
# 編按：另類的四捨五入操作？
arr_compare_2 = np.where(arr > 0.5, 1, 0)
print(arr_compare_2)

[0.22156569 0.31979874 0.93209828 0.20009645 0.9710366  0.91957347
 0.4694557  0.93476259 0.37515013 0.44126398]

[False False  True False  True  True False  True False False]

[0 0 1 0 1 1 0 1 0 0]


### 條件計算 + reshape

In [32]:
import numpy as np
arr = np.random.randint(0, 100, size = (4, 5))
print(arr)
print()

# 找出每一列的最大值
print(f"找出每一列的最大值")
for i in range(0, 4):
    arr_max = np.max(arr[i, ])
    print(f"第{i + 1}列的最大值：{arr_max}")
print()

# 調整 array 的形狀 (your_array.reshape(rows, columns))
rearr_1 = arr.reshape(20, )
print(rearr_1)
print(f"第一次轉換形狀：{np.shape(rearr_1)}")
print()

rearr_2 = rearr_1.reshape(5, 4)
print(rearr_2)
print(f"第二次轉換形狀：{np.shape(rearr_2)}")
print()

rearr_3 = rearr_2.reshape(2, 10)
print(rearr_3)
print(f"第三次轉換形狀：{np.shape(rearr_3)}")

[[75 39 80 63 39]
 [89 20 88 68 92]
 [45 70  9 92 40]
 [49 64 33  0 14]]

找出每一列的最大值
第1列的最大值：80
第2列的最大值：92
第3列的最大值：92
第4列的最大值：64

[75 39 80 63 39 89 20 88 68 92 45 70  9 92 40 49 64 33  0 14]
第一次轉換形狀：(20,)

[[75 39 80 63]
 [39 89 20 88]
 [68 92 45 70]
 [ 9 92 40 49]
 [64 33  0 14]]
第二次轉換形狀：(5, 4)

[[75 39 80 63 39 89 20 88 68 92]
 [45 70  9 92 40 49 64 33  0 14]]
第三次轉換形狀：(2, 10)


#### 補充：向量跟for迴圈的效率差異

In [14]:
import numpy as np
import time

start = time.time()
a = np.ones(10000)
b = np.arange(1, 10001)
print(a.dot(b))
end_1 = time.time()
total = 0
for i in range(1, 10001):
    total += i
print(total)
end_2 = time.time()

print(f"向量運算秒數：{round(end_1 - start, 5)}")
print(f"迴圈運算秒數：{round(end_2 - end_1, 5)}")    

50005000.0
50005000
向量運算秒數：0.0368
迴圈運算秒數：0.00299
